name: application-nginx-pipeline

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "dockerfile/podinfo/**"

permissions:
      id-token: write   
      contents: read    

run-name: podinfo → ecr → lambda

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # ---------- Lint & Test (go test ./... su Podinfo) ----------
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Clone Podinfo (for tests)
        run: |
          git clone --depth=1 https://github.com/stefanprodan/podinfo.git ./_podinfo
          cd _podinfo
          go test ./...